services:
  - type: web
    name: todo-react-node-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MY_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000